### ISSUE TITLE
 ERROR  /@ampproject/remapping@2.2.1 is an invalid relative dependency path

### ISSUE THREAD

**Issue by arunabhdas** [huntabyte/shadcn-svelte#122]
### Current Behavior

Getting the following error when I run 

```
pnpm install
```

Expected - 
No error

Actual - 

```
==> pnpm install
Scope: all 3 workspace projects
apps/www                                 |  WARN  Your pnpm-lock.yaml was generated by a newer version of pnpm. It is a compatible version but it might get downgraded to version 6.0
packages/cli                             |  WARN  Your pnpm-lock.yaml was generated by a newer version of pnpm. It is a compatible version but it might get downgraded to version 6.0
/Users/coder/repos/OpenLibreAI/githubrepos/shadcn-svelte/packages/cli:
 ERROR  /@ampproject/remapping@2.2.1 is an invalid relative dependency path

Error: /@ampproject/remapping@2.2.1 is an invalid relative dependency path
    at Object.parse2 [as parse] (/Users/coder/.nvm/versions/node/v16.20.0/lib/node_modules/pnpm/dist/pnpm.cjs:114405:15)
    at nameVerFromPkgSnapshot (/Users/coder/.nvm/versions/node/v16.20.0/lib/node_modules/pnpm/dist/pnpm.cjs:114514:28)
    at addPreferredVersionsFromLockfile (/Users/coder/.nvm/versions/node/v16.20.0/lib/node_modules/pnpm/dist/pnpm.cjs:187417:89)
    at getPreferredVersionsFromLockfileAndManifests (/Users/coder/.nvm/versions/node/v16.20.0/lib/node_modules/pnpm/dist/pnpm.cjs:187411:7)
    at _installInContext (/Users/coder/.nvm/versions/node/v16.20.0/lib/node_modules/pnpm/dist/pnpm.cjs:188337:142)
    at async installInContext (/Users/coder/.nvm/versions/node/v16.20.0/lib/node_modules/pnpm/dist/pnpm.cjs:188679:16)
    at async _install (/Users/coder/.nvm/versions/node/v16.20.0/lib/node_modules/pnpm/dist/pnpm.cjs:188202:25)
    at async mutateModules (/Users/coder/.nvm/versions/node/v16.20.0/lib/node_modules/pnpm/dist/pnpm.cjs:187924:23)
    at async install (/Users/coder/.nvm/versions/node/v16.20.0/lib/node_modules/pnpm/dist/pnpm.cjs:187850:45)
    at async /Users/coder/.nvm/versions/node/v16.20.0/lib/node_modules/pnpm/dist/pnpm.cjs:189502:31
 WARN  Your pnpm-lock.yaml was generated by a newer version of pnpm. It is a compatible version but it might get downgraded to version 6.0
```

### Expected Behavior

No errors and the project builds

### Steps To Reproduce

1. Clone this repo
2. cd shadcn-svelte
3. Run ```pnpm install```

**Comment by AdrianGonz97** [comment]
Related to https://github.com/pnpm/pnpm/issues/6648#issuecomment-1588863457. I haven't checked up on this issue recently, but fortunately it looks like it has a solution now.

**Comment by codelabspro** [comment]
Yes. It seems one has to update pnpm to 8.6.3 or higher using 

```
npm install -g pnpm
```

And then it is resolved

```
==> pnpm -v
8.6.3
```

Perhaps it will make sense to add that 

```
pnpm install 

pnpm dev
```

should be used instead of npm in the README.md or somewhere in the docs.
