### ISSUE TITLE
Failed to resolve entry for package "radix-svelte"

### ISSUE THREAD

**Issue by pruthivithejan** [huntabyte/shadcn-svelte#141]
### Current Behavior

I added the Authentication example on the website and save the file. The IDE does not show any errors but the console shows the below error and a 500 Internal Error in the website

`Internal server error: Failed to resolve entry for package "radix-svelte". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "radix-svelte" package
      at packageEntryFailure (file:///C:/Users/Pruthivi/Desktop/Javascript/wikum-dictionary/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23382:11)
      at resolvePackageEntry (file:///C:/Users/Pruthivi/Desktop/Javascript/wikum-dictionary/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23377:9)
      at tryNodeResolve (file:///C:/Users/Pruthivi/Desktop/Javascript/wikum-dictionary/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23121:20)
      at nodeImport (file:///C:/Users/Pruthivi/Desktop/Javascript/wikum-dictionary/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54433:26)    
      at ssrImport (file:///C:/Users/Pruthivi/Desktop/Javascript/wikum-dictionary/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54343:30)     
      at eval (C:/Users/Pruthivi/Desktop/Javascript/wikum-dictionary/src/lib/components/ui/label/Label.svelte:5:37)
      at async instantiateModule (file:///C:/Users/Pruthivi/Desktop/Javascript/wikum-dictionary/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54405:9) (x3)
Error: Failed to resolve entry for package "radix-svelte". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "radix-svelte" package
    at packageEntryFailure (file:///C:/Users/Pruthivi/Desktop/Javascript/wikum-dictionary/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23382:11)
    at resolvePackageEntry (file:///C:/Users/Pruthivi/Desktop/Javascript/wikum-dictionary/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23377:9)
    at tryNodeResolve (file:///C:/Users/Pruthivi/Desktop/Javascript/wikum-dictionary/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23121:20)  
    at nodeImport (file:///C:/Users/Pruthivi/Desktop/Javascript/wikum-dictionary/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54433:26)      
    at ssrImport (file:///C:/Users/Pruthivi/Desktop/Javascript/wikum-dictionary/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54343:30)       
    at eval (C:/Users/Pruthivi/Desktop/Javascript/wikum-dictionary/src/lib/components/ui/label/Label.svelte:5:37)
    at async instantiateModule (file:///C:/Users/Pruthivi/Desktop/Javascript/wikum-dictionary/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54405:9)`

### Expected Behavior

I expected the Sign-Up form to be displayed in the page and the rest of the application works fine

### Steps To Reproduce

1. I installed the neccesary Componnets
2. I added a '/signup' directory and added the code in the example to the '+page.svelte'
3. I save
4. and I see this error

**Comment by huntabyte** [comment]
Close as duplicate #125
