### ISSUE TITLE
asChild and let:builder is not working

### ISSUE THREAD

**Issue by lixelv** [huntabyte/shadcn-svelte#1423]
### Describe the bug

In next version of shdcn-svelte asChild and let:builder are giving the next error:
```
Svelte error: invalid_default_snippet
Cannot use `{@render children(...)}` if the parent component uses `let:` directives. Consider using a named snippet instead
    at invalid_default_snippet (Z:\GitHub\test\asChild-bug\now_working\node_modules\svelte\src\internal\shared\errors.js:11:17)
    at children (Z:\GitHub\test\asChild-bug\now_working\node_modules\bits-ui\dist\bits\menu\components\menu-trigger.svelte:34:21)
    at Module.Floating_layer_anchor [as default] (Z:\GitHub\test\asChild-bug\now_working\node_modules\bits-ui\dist\bits\utilities\floating-layer\components\floating-layer-anchor.svelte:15:18)
    at Module.Menu_trigger (Z:/GitHub/test/asChild-bug/now_working/node_modules/bits-ui/dist/bits/menu/components/menu-trigger.svelte:38:31)
    at children (Z:/GitHub/test/asChild-bug/now_working/src/routes/+page.svelte:17:26)
    at children (Z:\GitHub\test\asChild-bug\now_working\node_modules\bits-ui\dist\bits\menu\components\menu.svelte:48:19)
    at Module.Floating_layer [as default] (Z:\GitHub\test\asChild-bug\now_working\node_modules\bits-ui\dist\bits\utilities\floating-layer\components\floating-layer.svelte:10:18)
    at Module.Menu (Z:/GitHub/test/asChild-bug/now_working/node_modules/bits-ui/dist/bits/menu/components/menu.svelte:52:31)
    at _page (Z:/GitHub/test/asChild-bug/now_working/src/routes/+page.svelte:15:24)
    at children (Z:/GitHub/test/asChild-bug/now_working/.svelte-kit/generated/root.svelte:69:5)
```
But in latest version everything works normal.

### Reproduction

```svelte
<script lang="ts">
	import * as DropdownMenu from '$lib/components/ui/dropdown-menu/index.js';
	import { Button } from '$lib/components/ui/button';
</script>

<DropdownMenu.Root>
	<DropdownMenu.Trigger asChild let:builder>
		<Button builders={[builder]}>Trigger</Button>
	</DropdownMenu.Trigger>
	<DropdownMenu.Content>
		<DropdownMenu.Group>
			<DropdownMenu.Label>My Account</DropdownMenu.Label>
			<DropdownMenu.Separator />
			<DropdownMenu.Item>Profile</DropdownMenu.Item>
			<DropdownMenu.Item>Billing</DropdownMenu.Item>
			<DropdownMenu.Item>Team</DropdownMenu.Item>
			<DropdownMenu.Item>Subscription</DropdownMenu.Item>
		</DropdownMenu.Group>
	</DropdownMenu.Content>
</DropdownMenu.Root>
```

This code works in latest version, but in next I'm getting the error. Also here is repository with reproduction of this bug https://github.com/lixelv/shadcn-svelte-asChild-bug

### Logs

```bash
Z:\GitHub\test\asChild-bug\now_working>npm run dev

> now-working@0.0.1 dev
> vite dev

Forced re-optimization of dependencies

  VITE v5.4.10  ready in 812 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
Svelte error: invalid_default_snippet
Cannot use `{@render children(...)}` if the parent component uses `let:` directives. Consider using a named snippet instead
    at invalid_default_snippet (Z:\GitHub\test\asChild-bug\now_working\node_modules\svelte\src\internal\shared\errors.js:11:17)
    at children (Z:\GitHub\test\asChild-bug\now_working\node_modules\bits-ui\dist\bits\menu\components\menu-trigger.svelte:34:21)
    at Module.Floating_layer_anchor [as default] (Z:\GitHub\test\asChild-bug\now_working\node_modules\bits-ui\dist\bits\utilities\floating-layer\components\floating-layer-anchor.svelte:15:18)
    at Module.Menu_trigger (Z:/GitHub/test/asChild-bug/now_working/node_modules/bits-ui/dist/bits/menu/components/menu-trigger.svelte:38:31)
    at children (Z:/GitHub/test/asChild-bug/now_working/src/routes/+page.svelte:17:26)
    at children (Z:\GitHub\test\asChild-bug\now_working\node_modules\bits-ui\dist\bits\menu\components\menu.svelte:48:19)
    at Module.Floating_layer [as default] (Z:\GitHub\test\asChild-bug\now_working\node_modules\bits-ui\dist\bits\utilities\floating-layer\components\floating-layer.svelte:10:18)
    at Module.Menu (Z:/GitHub/test/asChild-bug/now_working/node_modules/bits-ui/dist/bits/menu/components/menu.svelte:52:31)
    at _page (Z:/GitHub/test/asChild-bug/now_working/src/routes/+page.svelte:15:24)
    at children (Z:/GitHub/test/asChild-bug/now_working/.svelte-kit/generated/root.svelte:69:5)
```

### System Info

```bash
System:
    OS: Windows 11 10.0.26052
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
    Memory: 20.61 GB / 31.87 GB
  Binaries:
    Node: 20.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.8)
    Internet Explorer: 11.0.26052.1000
```

### Severity

blocking all usage of shadcn-svelte

**Comment by huntabyte** [comment]
There is no longer `asChild` and `let:builder` - see https://next.bits-ui.com/docs/child-snippet

**Comment by DePasqualeOrg** [comment]
So what's the solution? How do I migrate this?

```svelte
<Sheet.Root bind:open>
  <Sheet.Trigger asChild>
    {#snippet children({ builder })}
      <Button
        builders={[builder]}
        variant="ghost"
      >
        <Menu class="h-5 w-5" />
        <span class="sr-only">Toggle menu</span>
      </Button>
    {/snippet}
  </Sheet.Trigger>
  <Sheet.Content side="left" class="pr-0">
    <!-- ... -->
  </Sheet.Content>
</Sheet.Root>
```

**Comment by ieedan** [comment]
You can rename builder to props then spread props on the Button

**Comment by ieedan** [comment]
This would probably be a good addition to the migration guide somewhere however it is all documented between bits-ui and the svelte 5 migration guide provided by svelte. 

If I can think of a nice way to add it in I can open a PR for it.

**Comment by ieedan** [comment]
@huntabyte would it make more sense to have that as part of the bits-ui migration guide and then link it in our docs?

**Comment by ieedan** [comment]
This is all documented btw https://next.bits-ui.com/docs/child-snippet

**Comment by DePasqualeOrg** [comment]
Thank you. My advice to anyone using these packages who is considering migrating to Svelte 5 is to wait until this all gets sorted out.

**Comment by ieedan** [comment]
> Thank you. My advice to anyone using these packages who is considering migrating to Svelte 5 is to wait until this all gets sorted out.

What exactly are you referring to that needs to be "sorted out"

**Comment by DePasqualeOrg** [comment]
I don't mean this as a critique at all, since I'm grateful for the work the maintainers do. I'm just sharing my anecdotal experience of trying to migrate to Svelte 5 and getting stuck spending 6+ hours trying to sort out some very complicated issues related to this package and the upcoming version. To save anyone else in a similar situation time, I recommend waiting until the upcoming version with Svelte 5 compatibility lands.

**Comment by ieedan** [comment]
> I don't mean this as a critique at all, since I'm grateful for the work the maintainers do. I'm just sharing my anecdotal experience of trying to migrate to Svelte 5 and getting stuck spending 6+ hours trying to sort out some very complicated issues related to this package and the upcoming version. To save anyone else in a similar situation time, I recommend waiting until the upcoming version with Svelte 5 compatibility lands.

If you are having issues with specific stuff I'd love to hear about it and hopefully there is something that can be done. This hasn't been my experience thusfar in migrating my projects.

**Comment by ieedan** [comment]
> I'll try to reconstruct my experience if it's helpful. I have a small SvelteKit project that uses shadcn-svelte, and I decided to try migrating to Svelte 5. I think the main difficulty is that running `sv migrate svelte-5` will also migrate the shadcn-svelte files (which currently use Svelte 4 syntax), and there are some issues there that need to be corrected, like the one I mentioned above. I also ran into issues with bits-ui, which needs to be set to `@next` with Svelte 5. Another issue was adding Svelte 5 in addition to Svelte 4 as a peer dependency in some of my own packages.
> 
> In the end, after several hours of troubleshooting those issues, I was able to get things to build, but my site didn't look right. So I decided to roll everything back to Svelte 4 and wait for the current versions of bits-ui and shadcn-svelte to be compatible with Svelte 5 before attempting the migration again.

Most of this is covered in the [Migration Guide](https://next.shadcn-svelte.com/docs/migration/svelte-5) I don't see a reason you need svelte 4 as a peer dependency in your project as most of the syntax should still work.
