### ISSUE TITLE
Reproduction Stackblitz Template

### ISSUE THREAD

**Issue by huntabyte** [huntabyte/shadcn-svelte#202]
Having a starter reproduction stackblitz template would be great for creating reproductions.

**Comment by theetherGit** [comment]
I tried to provide a stackblitz reproduction but unable to init shadcn-svelte. 
Error:
```bash
❯ npx shadcn-svelte@latest init
Need to install the following packages:
  shadcn-svelte@0.2.0
Ok to proceed? (y) y
This command assumes a SvelteKit project with TypeScript and Tailwind CSS.
If you don't have these, follow the manual steps at https://shadcn-svelte.com/docs/installation.

✔ Running this command will install dependencies and overwrite your existing tailwind.config.[cjs|js|ts]. Proceed? … yes
FetchError: request to https://shadcn-svelte.com/registry/styles/index.json failed, reason: socket hang up
    at ClientRequest.eval (/home/.npm/_npx/a9116f6e444a1e9e/node_modules/node-fetch/src/index.js:136:11)
    at EventEmitter.emit (node:events:45:8318)
    at TLSSocket.socketOnEnd (node:_http_client:230:6448)
    at EventEmitter.emit (node:events:45:8434)
    at endReadableNT (node:internal/streams/readable:96:14812)
    at _0x57f9b4 (https://sveltejskittemplatedefaultpzuh-ssko.w-credentialless.staticblitz.com/blitz.33975f1d.js:334:162128)
    at <anonymous> (https://sveltejskittemplatedefaultpzuh-ssko.w-credentialless.staticblitz.com/blitz.33975f1d.js:334:161885) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: undefined
}
Failed to fetch styles from registry.
```

**Comment by huntabyte** [comment]
Added a reproduction template: https://github.com/huntabyte/shadcn-repro-template/
