### ISSUE TITLE
Slider component broken with TypeError

### ISSUE THREAD

**Issue by jasongitmail** [huntabyte/shadcn-svelte#277]
### Current Behavior

Attempting to use a slider component throws an error in the project:

```sh
TypeError: Spread syntax requires ...iterable[Symbol.iterator] to be a function
    at returned (/Users/a/code/proj/node_modules/@melt-ui/svelte/dist/builders/slider/create.js:51:50)
    at eval (/Users/a/code/proj/node_modules/@melt-ui/svelte/dist/internal/helpers/builder.js:36:32)
    at sync (/Users/a/code/proj/node_modules/svelte/src/runtime/store/index.js:148:19)
    at eval (/Users/a/code/proj/node_modules/svelte/src/runtime/store/index.js:171:3)
    at Function.subscribe (/Users/a/code/proj/node_modules/svelte/src/runtime/store/index.js:79:11)
    at Module.subscribe (/Users/a/code/proj/node_modules/svelte/src/runtime/internal/utils.js:156:22)
    at eval (/Users/a/code/proj/node_modules/bits-ui/dist/bits/slider/components/SliderRange.svelte:18:46)
    at Object.$$render (/Users/a/code/proj/node_modules/svelte/src/runtime/internal/ssr.js:174:16)
    at Object.default (/Users/a/code/proj/src/lib/components/ui/slider/slider.svelte:42:199)
    at eval (/Users/a/code/proj/node_modules/bits-ui/dist/bits/slider/components/Slider.svelte:79:183)
```

This is probably with bits-ui or melt-ui, but I'm not sure which so reporting it here where I found it.

### Expected Behavior

Slide should load successfully.

### Steps To Reproduce

```
<script>
	import { Slider } from '$lib/components/ui/slider';
</script>


<Slider value={33} max={100} step={1} />
```

Error occurs when Slider component exists. The import itself doesn't cause an error, just attempted usage of it.

**Comment by huntabyte** [comment]
Hey @jasongitmail, the slider actually takes in an array for its value aligned with Melt UI, so it would be `<Slider value={[33]} />`. At the moment this is to handle multiple thumbs, although I've been considering updating the API in bits to just be the difference in the values if multiple thumbs are used. If you're also interested in that, feel free to create an issue in Bits!

Let me know if this fixes the issue you're having in the meantime!

**Comment by jasongitmail** [comment]
Good to know. Yep, it works as an array!

I copied that snippet from the docs, so it should be updated to an array value there too.

+1 on accepting either a number or an array, for most intuitive interface. Created an issue on [bits-ui](https://github.com/huntabyte/bits-ui/issues/112)  for that. Leaving this one open for the docs update.
