### ISSUE TITLE
Project not building use Cloudflare-Adapter

### ISSUE THREAD

**Issue by Cayllen** [huntabyte/shadcn-svelte#609]
### Describe the bug

When building my project via Cloudflare, I receive the following error output at cloudflare. But when I build my project on local, it works without problems via npm run build. Where could be the fault here?

```js
18:16:34.751 | Could not resolve "./input.svelte" from "src/lib/components/ui/input/index.ts"
-- | --
18:16:34.751 | file: /opt/buildhome/repo/src/lib/components/ui/input/index.ts
18:16:34.753 | error during build:
18:16:34.753 | RollupError: Could not resolve "./input.svelte" from "src/lib/components/ui/input/index.ts"
18:16:34.753 | at error (file:///opt/buildhome/repo/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
18:16:34.753 | at ModuleLoader.handleInvalidResolvedId (file:///opt/buildhome/repo/node_modules/rollup/dist/es/shared/node-entry.js:17997:24)
18:16:34.753 | at file:///opt/buildhome/repo/node_modules/rollup/dist/es/shared/node-entry.js:17957:26
18:16:34.785 | Failed: Error while executing user command. Exited with error code: 1
18:16:34.793 | Failed: build command exited with code: 1
18:16:35.877 | Failed: error occurred while running build command
```

The component sits here it should be via the installation instructions
<img width="291" alt="image" src="https://github.com/huntabyte/shadcn-svelte/assets/27898791/b5868f67-e23f-4fab-a6ff-e181fa8df5cc">

My svelte.config.js looks like this
```
import adapter from '@sveltejs/adapter-cloudflare';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';
import { importAssets } from 'svelte-preprocess-import-assets';



/** @type {import('@sveltejs/kit').Config}*/
const config = {
    // Consult https://kit.svelte.dev/docs/integrations#preprocessors
    // for more information about preprocessors
    extensions: ['.svelte'],
    kit: {

        adapter: adapter({ routes: { include: ['/*'], exclude: ['<all>', '/sitemap.xml'] } }),//'/sitemap.xml'

    },
    preprocess: [
        vitePreprocess(),
        importAssets({
            // Include URLs with specific extensions only
            urlFilter: (url) => /lib/.test(url)
        })
    ],
};
export default config;
```

### Reproduction

-

### System Info

```bash
System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M1
    Memory: 224.27 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.asdf/installs/nodejs/18.16.0/bin/node
    npm: 9.5.1 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 120.0.6099.199
    Safari: 17.1
  npmPackages:
    @sveltejs/kit: ^2.0.6 => 2.0.6 
    bits-ui: ^0.13.2 => 0.13.2 
    svelte: ^4.2.8 => 4.2.8
```

### Severity

blocking all usage of shadcn-svelte

**Comment by huntabyte** [comment]
> "src/lib/components/ui/input/index.ts"

Should be `src/lib/components/ui/input/index.js`

**Comment by Cayllen** [comment]
But eventually I import it like this
`	import { Input } from '$lib/components/ui/input';`
and when I use the CLI to install the files are saved like that

**Comment by Cayllen** [comment]
Can't really explain why it works now but things I tried out were:
https://stackoverflow.com/questions/75861521/bug-vercel-says-import-error-but-local-works-fine combined with deleting all components I installed and reinstalling them again (potentially related to my git not differing in capitalization)

adding this alias although $lib is unchanged for me

alias: {
            $components: 'src/lib/components'
        },
