### ISSUE TITLE
Import path error when deploying on vercel.

### ISSUE THREAD

**Issue by benjiegarcia** [huntabyte/shadcn-svelte#633]
### Describe the bug

There is no issue in local development, but once I deploy it on vercel it encounter a path error:
```
vite v5.0.11 building SSR bundle for production...
transforming...
✓ 163 modules transformed.
Could not resolve "./label.svelte" from "src/lib/components/ui/label/index.ts"
file: /vercel/path0/src/lib/components/ui/label/index.ts
error during build:
RollupError: Could not resolve "./label.svelte" from "src/lib/components/ui/label/index.ts"
    at error (file:///vercel/path0/node_modules/.pnpm/rollup@4.9.4/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at ModuleLoader.handleInvalidResolvedId (file:///vercel/path0/node_modules/.pnpm/rollup@4.9.4/node_modules/rollup/dist/es/shared/node-entry.js:18000:24)
    at file:///vercel/path0/node_modules/.pnpm/rollup@4.9.4/node_modules/rollup/dist/es/shared/node-entry.js:17960:26
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm run build" exited with 1
```

### Reproduction

I just installed the components on my project.

### Logs

```bash
vite v5.0.11 building SSR bundle for production...
transforming...
✓ 163 modules transformed.
Could not resolve "./label.svelte" from "src/lib/components/ui/label/index.ts"
file: /vercel/path0/src/lib/components/ui/label/index.ts
error during build:
RollupError: Could not resolve "./label.svelte" from "src/lib/components/ui/label/index.ts"
    at error (file:///vercel/path0/node_modules/.pnpm/rollup@4.9.4/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at ModuleLoader.handleInvalidResolvedId (file:///vercel/path0/node_modules/.pnpm/rollup@4.9.4/node_modules/rollup/dist/es/shared/node-entry.js:18000:24)
    at file:///vercel/path0/node_modules/.pnpm/rollup@4.9.4/node_modules/rollup/dist/es/shared/node-entry.js:17960:26
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm run build" exited with 1
```

### System Info

```bash
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 5.86 GB / 15.84 GB
  Binaries:
    Node: 20.3.0 - ~\.nvm\versions\node\v20.3.0\bin\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 9.6.7 - ~\.nvm\versions\node\v20.3.0\bin\npm.CMD
    pnpm: 8.6.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (120.0.2210.121)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/kit: ^2.2.0 => 2.3.0
    bits-ui: ^0.14.0 => 0.14.0
    svelte: ^4.2.8 => 4.2.8
```

### Severity

annoyance

**Comment by huntabyte** [comment]
You shouldn't use `/index.ts`, it should be `/index.js`

**Comment by benjiegarcia** [comment]
> You shouldn't use `/index.ts`, it should be `/index.js`

The CLI generates the index.ts file, Somehow moving all the generated files in /ui and removing the index.ts files. However I added a single .ts file for some types so other ui lib can use.

**Comment by huntabyte** [comment]
It's fine to have `index.ts` as the filename, but when importing into other components, you should specify `$lib/components/ui/whatever/index.js` (even if it's a .ts file)
