### ISSUE TITLE
Cli generated import casing is wrong

### ISSUE THREAD

**Issue by zhihengGet** [huntabyte/shadcn-svelte#846]
### Describe the bug

say we i have

Slider.svelte
index.ts

then in index.ts we have 

```
import Root from './slider.svelte';

export {
	Root,
	//
	Root as Slider
};

```

here we import 'slider.svelte' not 'Slider.svete' this cause issue with vercel builds 

plz consider to have the same casing for import and filename , either change the import name or filename

### Reproduction

- create a svelte 5 project with shad then deploy to vercel

### Logs

```bash
web:build: RollupError: Could not resolve "./avatar.svelte" from "src/lib/components/ui/avatar/index.ts"
web:build: file: /vercel/path0/apps/web/src/lib/components/ui/avatar/index.ts
web:build:     at getRollupEror (file:///vercel/path0/node_modules/.pnpm/rollup@4.12.0/node_modules/rollup/dist/es/shared/parseAst.js:375:41)
web:build:     at error (file:///vercel/path0/node_modules/.pnpm/rollup@4.12.0/node_modules/rollup/dist/es/shared/parseAst.js:372:42)
web:build:     at ModuleLoader.handleInvalidResolvedId (file:///vercel/path0/node_modules/.pnpm/rollup@4.12.0/node_modules/rollup/dist/es/shared/node-entry.js:18907:24)
web:build:     at file:///vercel/path0/node_modules/.pnpm/rollup@4.12.0/node_modules/rollup/dist/es/shared/node-entry.js:18867:26
web:build:  ELIFECYCLE  Command failed with exit code 1.
web:build: ERROR: command finished with error: command (/vercel/path0/apps/web) pnpm run build exited (1)
web#build: command (/vercel/path0/apps/web) pnpm run build exited (1)
  Tasks:    0 successful, 1 total
```

### System Info

```bash
ww
```

### Severity

annoyance

**Comment by huntabyte** [comment]
The CLI creates components with the names in lowercase. If you change it then its up to you to figure out how to fix your git casing issue.

We also don't support Svelte 5 until its stable.
