### ISSUE TITLE
Error max-redirect when try to npx any component

### ISSUE THREAD

**Issue by zulfiqarlaili** [huntabyte/shadcn-svelte#866]
### Describe the bug

I try to do `npx shadcn-svelte@latest add avatar` but i get error

```
npx shadcn-svelte@latest add avatar
FetchError: maximum redirect reached at: https://www.shadcn-svelte.com/registry/index.json
    at ClientRequest.<anonymous> (file:///Users/J0W432431K/.npm/_npx/a9116f6e444a1e9e/node_modules/node-fetch/src/index.js:179:15)
    at ClientRequest.emit (node:events:531:35)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:535:22)
    at TLSSocket.emit (node:events:531:35)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  type: 'max-redirect'
}
```

### Reproduction

1. create new project
2. `npx shadcn-svelte@latest add avatar` or any other component
3. Will get max-redirect error

### Logs

```bash
```
npx shadcn-svelte@latest add avatar
FetchError: maximum redirect reached at: https://www.shadcn-svelte.com/registry/index.json
    at ClientRequest.<anonymous> (file:///Users/J0W432431K/.npm/_npx/a9116f6e444a1e9e/node_modules/node-fetch/src/index.js:179:15)
    at ClientRequest.emit (node:events:531:35)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:535:22)
    at TLSSocket.emit (node:events:531:35)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  type: 'max-redirect'
}
```
```
```


### System Info

```bash
- node v21
- svelte 4
```

### Severity

annoyance

**Comment by zulfiqarlaili** [comment]
The issue resolve! thank you
